### ISSUE TITLE
Unexpected reserved world

### ISSUE THREAD

**Issue by janat08** [wffranco/vue-strap#109]
Vue is 2.1.10
npm: 4.5.0
Meteor.js
```
(!) Warning: node_modules/vue-strap/src/FormGroup.vue: tag <span> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/FormValidator.vue: tag <span> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/Option.vue: tag <li> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/Slider.vue: tag <div> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/TabGroup.vue: tag <span> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/FormGroup.vue: tag <span> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/FormValidator.vue: tag <span> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/Option.vue: tag <li> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/Slider.vue: tag <div> has no matching end tag.
   (!) Warning: node_modules/vue-strap/src/TabGroup.vue: tag <span> has no matching end tag.
W20170516-02:14:10.937(6)? (STDERR) /home/jk/Documents/garlic/.meteor/local/build/programs/server/packages/modules.js:3878                                                                                                      
W20170516-02:14:10.938(6)? (STDERR) export default {
W20170516-02:14:10.939(6)? (STDERR) ^^^^^^
W20170516-02:14:10.939(6)? (STDERR) 
W20170516-02:14:10.940(6)? (STDERR) SyntaxError: Unexpected reserved word
W20170516-02:14:10.940(6)? (STDERR)     at Object.exports.runInThisContext (vm.js:53:16)
W20170516-02:14:10.942(6)? (STDERR)     at /home/jk/Documents/garlic/.meteor/local/build/programs/server/boot.js:297:30                                                                                                         
W20170516-02:14:10.944(6)? (STDERR)     at Array.forEach (native)
W20170516-02:14:10.945(6)? (STDERR)     at Function._.each._.forEach (/home/jk/.meteor/packages/meteor-tool/.1.4.4_2.14bttwj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)                                                                                     
W20170516-02:14:10.945(6)? (STDERR)     at /home/jk/Documents/garlic/.meteor/local/build/programs/server/boot.js:128:5                                                                                                          
W20170516-02:14:10.946(6)? (STDERR)     at /home/jk/Documents/garlic/.meteor/local/build/programs/server/boot.js:352:5                                                                                                          
W20170516-02:14:10.946(6)? (STDERR)     at Function.run (/home/jk/Documents/garlic/.meteor/local/build/programs/server/profile.js:510:12)                                                                                       
W20170516-02:14:10.947(6)? (STDERR)     at /home/jk/Documents/garlic/.meteor/local/build/programs/server/boot.js:351:11                                                                                                         
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by janat08** [comment]
Meteor doesn't run webpack. So that webpack stuff is there (ur repo).
